### ISSUE TITLE
Add support for SSL authentication

### ISSUE THREAD

**Issue by hichemelhic** [NathanChen198/streamlit-ldap-authenticator#2]
It would be good to add a parameter to configure SSL authentication here:
https://github.com/NathanChen198/streamlit-ldap-authenticator/blob/main/streamlit_ldap_authenticator/ldap_authenticate.py#L65

See implementation of SSL authentication in ldap3 here:
https://ldap3.readthedocs.io/en/latest/ssltls.html?highlight=ssl

**Comment by NathanChen198** [comment]
Thanks for pointing that out.
I added the **basic SSL authentication** as per your suggestion and update the release to ver0.0.5
